import {addChineseUnit, treeFilter, treeWalk} from "../module/util";
import * as should from "should";

describe("测试用例",()=>{
    describe("树方法", () => {
        let tree = [
            {
                children: [
                    {
                        children: [

                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8508,
                                name: "SSE_KCB_ISSUER_ASSETS_APPRA_REVIEW_ORG",
                                nameCn: "资产评估复核机构",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8508"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8509,
                                name: "SSE_KCB_ISSUER_ATTORNEY",
                                nameCn: "发行人律师",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8509"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8510,
                                name: "SSE_KCB_ISSUER_AUDIT_ORG",
                                nameCn: "审计机构",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8510"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8511,
                                name: "SSE_KCB_ISSUER_BASIC_INTRO",
                                nameCn: "发行人基本情况",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8511"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8512,
                                name: "SSE_KCB_ISSUER_CAPITAL_VER_ORG",
                                nameCn: "验资机构",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8512"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8513,
                                name: "SSE_KCB_ISSUE_BASIC_INFO",
                                nameCn: "本次发行的基本情况",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8513"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8514,
                                name: "SSE_KCB_ISSUE_GENERAL_SITUATION",
                                nameCn: "发行基本情况",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8514"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8515,
                                name: "SSE_KCB_ISSUE_INTERMEDIARY_ORG",
                                nameCn: "中介机构概况",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8515"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8516,
                                name: "SSE_KCB_ISSUE_TITLEPAGE",
                                nameCn: "发行概况(扉页)",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8516"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8517,
                                name: "SSE_KCB_LEAD_UNDER",
                                nameCn: "主承销商",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8517"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8518,
                                name: "SSE_KCB_LISTING_STD",
                                nameCn: "上市标准",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8518"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8519,
                                name: "SSE_KCB_MAIN_HOLDER",
                                nameCn: "前十名股东",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8519"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8520,
                                name: "SSE_KCB_MAIN_HOLDER_POST",
                                nameCn: "前十自然股东",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8520"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8521,
                                name: "SSE_KCB_MAJOR_ASS_RESTRUCTURING",
                                nameCn: "重大资产重组情况",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8521"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8522,
                                name: "SSE_KCB_MAR_SAL",
                                nameCn: "董监高核从发行人及其关联企业领取薪酬情况",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8522"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8523,
                                name: "SSE_KCB_MAR_SAL_RATIO",
                                nameCn: "董监高核报告期内薪酬及与利润总额占比",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8523"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8524,
                                name: "SSE_KCB_OSC",
                                nameCn: "发行人股权结构图",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8524"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8525,
                                name: "SSE_KCB_OTHER_ORG",
                                nameCn: "中介机构_其他机构",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8525"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8526,
                                name: "SSE_KCB_OVERVIEW_ISSUER_BASIC_INTRO",
                                nameCn: "发行人基本情况(概览)",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8526"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8527,
                                name: "SSE_KCB_PRO_CONTROL",
                                nameCn: "协议控制",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8527"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8528,
                                name: "SSE_KCB_RAISED_PURPOSE",
                                nameCn: "募集资金用途",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8528"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8529,
                                name: "SSE_KCB_RAISED_USE_CONDITION",
                                nameCn: "募集资金总量及使用情况",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8529"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8530,
                                name: "SSE_KCB_RD_EMP",
                                nameCn: "研发人员情况",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8530"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8531,
                                name: "SSE_KCB_REAL_CONCERTED",
                                nameCn: "实际控制人的一致行动人",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8531"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8532,
                                name: "SSE_KCB_REL_PARTY_TRANS",
                                nameCn: "关联交易情况",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8532"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8533,
                                name: "SSE_KCB_RISK_FACTOR",
                                nameCn: "风险因素",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8533"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8534,
                                name: "SSE_KCB_SHA_CORRELATION",
                                nameCn: "股东关系",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8534"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8535,
                                name: "SSE_KCB_SPONSOR_ATTORNEY",
                                nameCn: "保荐人律师",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8535"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8536,
                                name: "SSE_KCB_SPONSOR_ORG",
                                nameCn: "保荐人",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8536"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8537,
                                name: "SSE_KCB_SUB_BRANCH",
                                nameCn: "发行人分支机构基本情况",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8537"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8538,
                                name: "SSE_KCB_SUB_FIN_STAT",
                                nameCn: "发行人子公司最近一年及一期末的资产及利润情况",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8538"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8539,
                                name: "SSE_KCB_SUB_SHAREHOLDING",
                                nameCn: "发行人参股公司基本情况",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8539"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8540,
                                name: "SSE_KCB_SUB_SUBSIDIARY",
                                nameCn: "发行人控股子公司基本情况",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8540"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8541,
                                name: "SSE_KCB_TOT_EMP",
                                nameCn: "员工总数",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8541"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8542,
                                name: "SSE_KCB_VOTE_CONTROL",
                                nameCn: "特别表决",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8542"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8543,
                                name: "STAR_AGENCY_BASICINFO",
                                nameCn: "中介机构",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8543"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8544,
                                name: "STAR_AGENCY_EMPLOYEE",
                                nameCn: "中介机构人员",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8544"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8545,
                                name: "STAR_AGENCY_LIST",
                                nameCn: "中介参与方",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8545"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8546,
                                name: "STAR_CORP_BASICINFO",
                                nameCn: "公司基本资料",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8546"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8547,
                                name: "STAR_CORP_INDUSTRY",
                                nameCn: "所属行业",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8547"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8548,
                                name: "STAR_EVENT_INVESTIGATION",
                                nameCn: "立案调查",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8548"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8549,
                                name: "STAR_EVENT_IVIOLATION",
                                nameCn: "违规",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8549"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8550,
                                name: "STAR_EVENT_LAWSUIT",
                                nameCn: "重大诉讼",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8550"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8551,
                                name: "STAR_EVENT_MA",
                                nameCn: "重大资产重组",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8551"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8552,
                                name: "STAR_EVENT_MADETAIL",
                                nameCn: "重大资产重组详情",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8552"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8553,
                                name: "STAR_FIN_AUDITOPINION",
                                nameCn: "审计意见",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8553"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8554,
                                name: "STAR_FIN_BALANCE",
                                nameCn: "资产负债表",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8554"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8555,
                                name: "STAR_FIN_BALANCE1",
                                nameCn: "资产负债表_更新数据",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8555"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8556,
                                name: "STAR_FIN_CASHFLOW",
                                nameCn: "现金流量表",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8556"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8557,
                                name: "STAR_FIN_CUSTOMER5",
                                nameCn: "前五客户情况表",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8557"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8558,
                                name: "STAR_FIN_GUARANTEE",
                                nameCn: "对外担保情况表",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8558"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8559,
                                name: "STAR_FIN_INCOME",
                                nameCn: "利润表",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8559"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8560,
                                name: "STAR_FIN_INDEX",
                                nameCn: "公布重要财务指标表",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8560"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8561,
                                name: "STAR_FIN_NONRECURRING",
                                nameCn: "非经常性损益表",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8561"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8562,
                                name: "STAR_FIN_POLICY",
                                nameCn: "重要会计政策和会计变更表",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8562"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8563,
                                name: "STAR_FIN_RDPROJECT",
                                nameCn: "研发投入项目表",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8563"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8564,
                                name: "STAR_FIN_RD_INDUSTRY_CONTRAST",
                                nameCn: "研发费用率与同行业可比公司的对比",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8564"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8565,
                                name: "STAR_FIN_SALESSEGMENT",
                                nameCn: "主营业务构成表",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8565"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8566,
                                name: "STAR_FIN_SHAREBASEDPAYMENT",
                                nameCn: "股份支付情况表",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8566"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8567,
                                name: "STAR_FIN_SUPPLIER5",
                                nameCn: "前五供应商情况表",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8567"
                            },
                            {
                                children: [],
                                dbId: 39,
                                dbName: "data_center_kcb_bdl_pre",
                                dbNameCn: "科创版",
                                haveRight: false,
                                id: 8568,
                                name: "STAR_GOV_COMPETITION",
                                nameCn: "同业竞争说明",
                                parentUniqueId: "39_-1",
                                tableCount: 0,
                                type: "table",
                                uniqueId: "39_-1_8568"
                            },
                        ],
                        dbId: 39,
                        dbName: "data_center_kcb_bdl_pre",
                        dbNameCn: "科创版",
                        id: -1,
                        name: "",
                        nameCn: "未分类",
                        parentUniqueId: "39",
                        tableCount: 135,
                        type: "table_type",
                        uniqueId: "39_-1"
                    }
                ],
                dbId: 39,
                dbName: "data_center_kcb_bdl_pre",
                dbNameCn: "科创版",
                id: 39,
                name: "data_center_kcb_bdl_pre",
                nameCn: "科创版",
                parentUniqueId: "-1",
                tableCount: 135,
                type: "database",
                uniqueId: "39"
            },
            {
                dbId: 39,
                dbName: "data_center_kcb_bdl_pre",
                dbNameCn: "科创版",
                id: 39,
                name: "data_center_kcb_bdl_pre",
                nameCn: "科创版",
                parentUniqueId: "-1",
                tableCount: 135,
                type: "database",
                uniqueId: "36"
            },
            {
                dbId: 39,
                dbName: "data_center_kcb_bdl_pre",
                dbNameCn: "科创版",
                id: 39,
                name: "data_center_kcb_bdl_pre",
                nameCn: "科创版",
                parentUniqueId: "-1",
                tableCount: 135,
                type: "database",
                uniqueId: "36"
            },
        ];
        it('should return corrent value', function () {

            let value = treeFilter(tree, (node) => {
                return node.type === "table";
            });
            let boolean = value.every(value1 => value1.type === "table");
            should.equal(boolean, true);
        });
        it('should correct for each', function () {
            let count = 0;
            let value = treeWalk(tree, (node) => {
                count += 1;
            });
            should.equal(count,65)
        });
    });
    describe("钱加单位",()=>{
        it('should return 1.222万', function () {
            should.equal(addChineseUnit(12222,3), "1.222万");
        });
        it('should return 1.82万', function () {
            let money = addChineseUnit(18242, 2);
            // should.equal(money, "1.82万");
            expect(money).toEqual("1.82万");
        });
    })
})
